apiVersion: apps/v1
kind: Deployment
metadata:
  name: kui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kui
  template:
    metadata:
      labels:
        app : kui 
    spec:
      containers:
        - name: ui
          image: vasikaran/fse:ui-estockmarket
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          
---
 
apiVersion: v1
kind: Service
metadata:
  name: kui
spec:
  selector:
    app: kui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer